# Identificadores del proyecto
sonar.projectKey=Henry_Quispe_t1
sonar.sources=.

# Servidor de SonarQube
sonar.host.url=https://sonarqube.ingsoftware.lat/
sonar.token=sqa_4e296de25b56b315988b9a9dfd137d2b4f97e7c3

# Exclusiones (ignorar carpetas generadas o de librerias)
sonar.exclusions=node_modules/**, backend/target/**, frontend/dist/**, frontend/build/**, .venv/**, old/**, **/*.py

# Configuracion especifica para Java (OBLIGATORIO para escanear Spring Boot)
sonar.java.binaries=backend/target/classes

# Configuracion de pruebas
sonar.tests=.
sonar.test.inclusions=**/src/test/**, **/*.test.js, **/*.test.jsx

# Reporte de cobertura JaCoCo (generado por: ./mvnw verify)
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
